### ISSUE TITLE
Only movies supported at the moment

### ISSUE THREAD

**Issue by TJFJefroy** [ThePBone/TVNow-Scraper#1]
Ich bekomme den fehler Only movies supported at the moment
wenn ich versuche vampires los muertos (https://www.tvnow.de/filme/john-carpenters-vampires-los-muertos-15895) runterzuladen

**Comment by timschneeb** [comment]
Leider hat sich die undokumentierte API von TVNow für Filme verändert. Ihre Filme sind jetzt nicht mehr am ganzen Stück, sondern sind in einzelne Teile unterteilt. Also werden jetzt Filme wie Serien behandelt, nur dass statt Serienepisoden jetzt die einzelnen Filmabschnitte gedownloadet werden. Da ich den Downloader für Serien nie implementiert hatte, können jetzt leider auch keine Filme mehr heruntergeladen werden.

Das Projekt ist mehr oder weniger auf Eis gelegt und wird (zumindest zurzeit) nicht weiterentwickelt.
